from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
from decimal import Decimal
from typing import Optional
from app.database import SessionLocal
from app import schemas, models

router = APIRouter(prefix="/api/dashboard", tags=["Dashboard Analytics"])

# Dependency to get DB session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# =================================================================
# FETCH LIVE REAL-TIME METRICS SUMMARY
# =================================================================
@router.get("/analytics", response_model=schemas.DashboardAnalytics)
def get_dashboard_analytics(db: Session = Depends(get_db)):
    try:
        # 1. Calculate Total Gross Sales Revenue generated by invoices
        sales_rev = db.query(func.sum(models.Order.total_amount)).scalar() or Decimal("0.00")
        
        # 2. Calculate Total Cash/Liquid received inside the store drawer
        liquid_cash = db.query(func.sum(models.FinanceLedger.amount)).filter(
            models.FinanceLedger.type == "INCOME"
        ).scalar() or Decimal("0.00")
        
        # 3. Calculate Total Active Credit Due out in the market (Udhaar)
        market_debt = db.query(func.sum(models.Customer.total_credit_due)).scalar() or Decimal("0.00")
        
        # 4. Calculate Total Sunk Expenses spent on procuring stock inventory items
        purchase_spend = db.query(func.sum(models.FinanceLedger.amount)).filter(
            models.FinanceLedger.type == "EXPENSE"
        ).scalar() or Decimal("0.00")
        
        # 5. Calculate Overall Net Operating Margin Profit
        net_profit = sales_rev - purchase_spend

        # 6. Fetch Low Stock Items (Flagging products running low)
        # Using a fallback threshold of 5 units for notification triggers
        low_stock_threshold = Decimal("5.00")
        low_stock_query = db.query(models.Product).filter(
            models.Product.current_quantity <= low_stock_threshold
        ).all()
        
        low_stock_count = len(low_stock_query)
        
        # Format the low stock responses to match schemas.LowStockAlert formatting rules
        low_stock_alerts = [
            schemas.LowStockAlert(
                product_id=p.id,
                product_name=p.name,
                current_quantity=p.current_quantity,
                brand=p.brand
            ) for p in low_stock_query
        ]

        # 7. Identify the Top Selling Product item across processing lines
        top_product_record = db.query(
            models.OrderItem.product_id,
            func.sum(models.OrderItem.quantity).label("total_sold")
        ).group_by(models.OrderItem.product_id).order_by(func.sum(models.OrderItem.quantity).desc()).first()

        top_selling_product = None
        if top_product_record:
            best_product = db.query(models.Product).filter(models.Product.id == top_product_record.product_id).first()
            if best_product:
                top_selling_product = schemas.ProductSearchResponse(
                    id=best_product.id,
                    name=best_product.name,
                    brand=best_product.brand,
                    barcode=best_product.barcode,
                    unit_type=best_product.unit_type,
                    selling_price=best_product.selling_price,
                    current_quantity=best_product.current_quantity
                )

        # Pack aggregated variables neatly into schemas.DashboardAnalytics structure template
        return schemas.DashboardAnalytics(
            total_sales_revenue=sales_rev,
            total_liquid_received=liquid_cash,
            total_market_debt=market_debt,
            total_purchase_spend=purchase_spend,
            overall_net_profit=net_profit,
            top_selling_product=top_selling_product,
            low_stock_count=low_stock_count,
            low_stock_alerts=low_stock_alerts
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to compile analytics dashboard metrics: {str(e)}")