from sqlalchemy import Column, Integer, String, Numeric, ForeignKey, DateTime, Boolean
from sqlalchemy.orm import relationship
import datetime
from app.database import Base

# 1. CATEGORY MODEL
class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    parent_id = Column(Integer, ForeignKey("categories.id"), nullable=True)

    # Self-referential relationship for nested categories (e.g., Electronics -> Phones)
    subcategories = relationship("Category", backref="parent", remote_side=[id])
    products = relationship("Product", back_populates="category")


# 2. PRODUCT MODEL
class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    
    # Financial fields updated to secure Numeric types
    cost_price = Column(Numeric(10, 2), nullable=False)
    selling_price = Column(Numeric(10, 2), nullable=False)
    
    current_quantity = Column(Integer, default=0)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False)

    category = relationship("Category", back_populates="products")


# 3. ORDER MODEL
class Order(Base):
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    total_amount = Column(Numeric(10, 2), nullable=False)  # Updated to Numeric
    payment_method = Column(String, nullable=False)       # e.g., "CASH", "ONLINE"
    payment_status = Column(String, default="PAID")        # e.g., "PAID", "PENDING"
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)

    items = relationship("OrderItem", back_populates="order")


# 4. ORDER ITEM MODEL (Receipt Breakdown)
class OrderItem(Base):
    __tablename__ = "order_items"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=False)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)
    quantity = Column(Integer, nullable=False)
    unit_price = Column(Numeric(10, 2), nullable=False)   # Updated to Numeric

    order = relationship("Order", back_populates="items")


# 5. STOCK TRANSACTION MODEL (Audit Log)
class StockTransaction(Base):
    __tablename__ = "stock_transactions"

    id = Column(Integer, primary_key=True, index=True)
    product_id = Column(Integer, ForeignKey("products.id"), nullable=False)
    type = Column(String, nullable=False)                  # "SALE", "RESTOCK", "WASTE"
    quantity_changed = Column(Integer, nullable=False)     # Negative for sales, positive for refills
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    notes = Column(String, nullable=True)


# 6. FINANCE LEDGER MODEL (Cash Book)
class FinanceLedger(Base):
    __tablename__ = "finance_ledger"

    id = Column(Integer, primary_key=True, index=True)
    type = Column(String, nullable=False)                  # "INCOME" or "EXPENSE"
    amount = Column(Numeric(10, 2), nullable=False)        # Updated to Numeric
    category = Column(String, nullable=False)              # e.g., "Customer Sale", "Rent", "Electricity"
    is_automated = Column(Boolean, default=True)           # True if generated by checkout, False if manual
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    notes = Column(String, nullable=True)